#pragma once
#include "RetainedEdgeTreatmentAttribute.hxx"
#include "RetainedSolidBinaryDriver.hxx"
#include <BinMDF_ADriverTable.hxx>
#include <BinMNaming_NamedShapeDriver.hxx>
#include <BinObjMgt_Persistent.hxx>
#include <BinTools_ShapeReader.hxx>
#include <BinTools_ShapeSet.hxx>
#include <BinTools_ShapeWriter.hxx>
#include <TDocStd_FormatVersion.hxx>

Standard_Boolean Core3DValidateRetainedEdgeTreatmentDocument(const Handle(TDocStd_Document)&);
namespace core3d::retained_edge_treatment {
class BinaryDriver final:public BinMDF_ADriver {
public:
    BinaryDriver(const Handle(Message_Messenger)&m,Handle(BinMNaming_NamedShapeDriver) shapes,std::shared_ptr<retained_solid::ReadBudget> budget,void(*reject)()noexcept=nullptr):BinMDF_ADriver(m,STANDARD_TYPE(Attribute)->Name()),shapes_(std::move(shapes)),budget_(std::move(budget)),reject_(reject){}
    Handle(TDF_Attribute) NewEmpty()const override{return new Attribute;}
    const Handle(Standard_Type)& SourceType()const override{return STANDARD_TYPE(Attribute);}
    Standard_Boolean Paste(const BinObjMgt_Persistent&source,const Handle(TDF_Attribute)&target,BinObjMgt_RRelocationTable&relocation)const override{
        try{auto a=Handle(Attribute)::DownCast(target);if(a.IsNull()||a->value_||a->valueR2_||shapes_.IsNull()||!budget_||budget_->rejected||relocation.GetHeaderData().IsNull())return Refuse();const auto version=relocation.GetHeaderData()->StorageVersion();if(!version.IsIntegerValue()||version.IntegerValue()<TDocStd_FormatVersion_VERSION_10||version.IntegerValue()>TDocStd_FormatVersion_CURRENT)return Refuse();Standard_Integer schema=0,count=0,mode=-1;if(!(source>>schema>>count>>mode)||schema!=1||count<=0||count>Standard_Integer(MaximumEnvelopeBytes)||(mode!=0&&mode!=1)||mode!=int(shapes_->IsQuickPart())||std::size_t(count)>budget_->limit-budget_->envelopeBytes)return Refuse();std::vector<std::uint8_t>bytes(static_cast<std::size_t>(count));if(!source.GetByteArray(bytes.data(),count))return Refuse();Refusal refusal;std::optional<Definition>definition;std::optional<r2::Definition>definitionR2;const bool isR2=bytes.size()>60&&std::memcmp(bytes.data(),"SYET\2\0\0\0",8)==0&&bytes[60]==3;if(isR2){if(!r2::Decode(bytes,definitionR2,refusal)||!definitionR2)return Refuse();}else if(!Decode(bytes,definition,refusal)||!definition)return Refuse();TopoDS_Shape base;auto*shared=shapes_->ShapeSet(Standard_True);if(!shared)return Refuse();if(mode){auto*stream=const_cast<BinObjMgt_Persistent&>(source).GetIStream();if(!stream||!dynamic_cast<BinTools_ShapeReader*>(shared))return Refuse();shared->Read(*stream,base);}else{auto*set=dynamic_cast<BinTools_ShapeSet*>(shared);Standard_Integer shape=0,location=-1,orientation=-1;if(!set||!(source>>shape>>location>>orientation)||shape<=0||shape>set->NbShapes()||location<0||location>set->Locations().NbLocations())return Refuse();base=set->Shape(shape);base.Location(set->Locations().Location(location),Standard_False);base.Orientation(TopAbs_Orientation(orientation));}if(base.IsNull()||base.ShapeType()!=TopAbs_SOLID||base.Orientation()!=TopAbs_FORWARD)return Refuse();if(isR2){auto value=std::make_shared<PayloadR2>();value->definition=std::move(*definitionR2);value->bytes=std::move(bytes);value->base=std::move(base);a->valueR2_=std::move(value);}else{auto value=std::make_shared<Payload>();value->definition=std::move(*definition);value->bytes=std::move(bytes);value->base=std::move(base);a->value_=std::move(value);}budget_->envelopeBytes+=std::size_t(count);++budget_->records;return Standard_True;}catch(...){return Refuse();}}
    void Paste(const Handle(TDF_Attribute)&source,BinObjMgt_Persistent&target,BinObjMgt_SRelocationTable&)const override{auto a=Handle(Attribute)::DownCast(source);if(a.IsNull()||bool(a->value_)==bool(a->valueR2_)||shapes_.IsNull())Standard_Failure::Raise("B1 writer source");std::vector<std::uint8_t>encoded;Refusal refusal;TopoDS_Shape base;if(a->value_){if(a->value_->base.IsNull()||!Encode(a->value_->definition,encoded,refusal)||encoded!=a->value_->bytes)Standard_Failure::Raise("B1 writer envelope");base=a->value_->base;}else{if(a->valueR2_->base.IsNull()||!r2::Encode(a->valueR2_->definition,encoded,refusal)||encoded!=a->valueR2_->bytes)Standard_Failure::Raise("B1 r2 writer envelope");base=a->valueR2_->base;}target<<Standard_Integer(1)<<Standard_Integer(encoded.size())<<Standard_Integer(shapes_->IsQuickPart()?1:0);target.PutByteArray(encoded.data(),Standard_Integer(encoded.size()));auto*shared=shapes_->ShapeSet(Standard_False);if(!shared)Standard_Failure::Raise("B1 shared writer");if(shapes_->IsQuickPart()){auto*stream=target.GetOStream();if(!stream||!dynamic_cast<BinTools_ShapeWriter*>(shared))Standard_Failure::Raise("B1 direct writer");shared->Write(base,*stream);}else{auto*set=dynamic_cast<BinTools_ShapeSet*>(shared);if(!set)Standard_Failure::Raise("B1 indexed writer");target<<set->Add(base)<<set->Locations().Index(base.Location())<<Standard_Integer(base.Orientation());}}
private:Standard_Boolean Refuse()const noexcept{if(budget_)budget_->rejected=true;if(reject_)reject_();return Standard_False;}Handle(BinMNaming_NamedShapeDriver)shapes_;std::shared_ptr<retained_solid::ReadBudget>budget_;void(*reject_)()noexcept;
};
inline void Register(const Handle(BinMDF_ADriverTable)&table,const Handle(Message_Messenger)&messenger,const std::shared_ptr<retained_solid::ReadBudget>&budget,void(*reject)()noexcept){Handle(BinMDF_ADriver)found;table->GetDriver(STANDARD_TYPE(TNaming_NamedShape),found);auto shapes=Handle(BinMNaming_NamedShapeDriver)::DownCast(found);if(shapes.IsNull())Standard_Failure::Raise("B1 shared driver missing");table->AddDriver(new BinaryDriver(messenger,shapes,budget,reject));}
template<class Base>class StorageDriver:public Base{public:Handle(BinMDF_ADriverTable)AttributeDrivers(const Handle(Message_Messenger)&m)override{auto table=Base::AttributeDrivers(m);retained_edge_treatment::Register(table,m,std::make_shared<retained_solid::ReadBudget>(),nullptr);return table;}void Write(const Handle(CDM_Document)&d,const TCollection_ExtendedString&f,const Message_ProgressRange&p=Message_ProgressRange())override{Prepare(d);Base::Write(d,f,p);}void Write(const Handle(CDM_Document)&d,Standard_OStream&s,const Message_ProgressRange&p=Message_ProgressRange())override{Prepare(d);Base::Write(d,s,p);}private:static void Prepare(const Handle(CDM_Document)&value){auto d=Handle(TDocStd_Document)::DownCast(value);if(d.IsNull()||!Core3DValidateRetainedEdgeTreatmentDocument(d))Standard_Failure::Raise("B1 writer validation");}};
} // namespace core3d::retained_edge_treatment
