#pragma once
// Proposed native arithmetic and complete value-codec admission regressions.
// Not registered, compiled, or run. No actual retained shape/owner is invented.
#include "SavedCutSourceBoreClearanceProbe.hxx"
namespace core3d::saved_cut_bore_clearance::interval_probe {
using Rows=probe::Rows;
inline Rows Arithmetic(){
    using namespace detail;Rows rows;
    auto add=[&](const std::string& key,bool value){rows.emplace_back(key,value);};
    const double nan=std::numeric_limits<double>::quiet_NaN(),inf=std::numeric_limits<double>::infinity();
    const double huge=std::numeric_limits<double>::max(),tiny=std::numeric_limits<double>::denorm_min();
    { const I bad=I(1,0);
      add("reversed/neg",!good(neg(bad)));
      add("reversed/square",!good(sq(bad)));
      add("reversed/root",!good(root(bad)));
      add("reversed/absolute",!good(abs(bad)));
      add("reversed/widen",!good(widen(bad,1)));
      add("reversed/add-left",!good(detail::add(bad,I(2))));
      add("reversed/add-right",!good(detail::add(I(2),bad)));
      add("reversed/subtract-left",!good(sub(bad,I(2))));
      add("reversed/subtract-right",!good(sub(I(2),bad)));
      add("reversed/multiply-left",!good(mul(bad,I(2))));
      add("reversed/multiply-right",!good(mul(I(2),bad)));
      add("reversed/divide-left",!good(div(bad,I(2))));
      add("reversed/divide-right",!good(div(I(2),bad)));
      add("reversed/minimum-left",!good(minimum(bad,I(2))));
      add("reversed/minimum-right",!good(minimum(I(2),bad)));
      add("reversed/maximum-left",!good(maximum(bad,I(2))));
      add("reversed/maximum-right",!good(maximum(I(2),bad)));
      add("reversed/norm-left",!good(norm(bad,I(2))));
      add("reversed/norm-right",!good(norm(I(2),bad)));
      add("reversed/midpoint",!std::isfinite(midpoint(bad)));
      add("reversed/mag",!std::isfinite(mag(bad)));
    }
    { const I bad=I(nan,2);
      add("nan-low/neg",!good(neg(bad)));
      add("nan-low/square",!good(sq(bad)));
      add("nan-low/root",!good(root(bad)));
      add("nan-low/absolute",!good(abs(bad)));
      add("nan-low/widen",!good(widen(bad,1)));
      add("nan-low/add-left",!good(detail::add(bad,I(2))));
      add("nan-low/add-right",!good(detail::add(I(2),bad)));
      add("nan-low/subtract-left",!good(sub(bad,I(2))));
      add("nan-low/subtract-right",!good(sub(I(2),bad)));
      add("nan-low/multiply-left",!good(mul(bad,I(2))));
      add("nan-low/multiply-right",!good(mul(I(2),bad)));
      add("nan-low/divide-left",!good(div(bad,I(2))));
      add("nan-low/divide-right",!good(div(I(2),bad)));
      add("nan-low/minimum-left",!good(minimum(bad,I(2))));
      add("nan-low/minimum-right",!good(minimum(I(2),bad)));
      add("nan-low/maximum-left",!good(maximum(bad,I(2))));
      add("nan-low/maximum-right",!good(maximum(I(2),bad)));
      add("nan-low/norm-left",!good(norm(bad,I(2))));
      add("nan-low/norm-right",!good(norm(I(2),bad)));
      add("nan-low/midpoint",!std::isfinite(midpoint(bad)));
      add("nan-low/mag",!std::isfinite(mag(bad)));
    }
    { const I bad=I(1,nan);
      add("nan-high/neg",!good(neg(bad)));
      add("nan-high/square",!good(sq(bad)));
      add("nan-high/root",!good(root(bad)));
      add("nan-high/absolute",!good(abs(bad)));
      add("nan-high/widen",!good(widen(bad,1)));
      add("nan-high/add-left",!good(detail::add(bad,I(2))));
      add("nan-high/add-right",!good(detail::add(I(2),bad)));
      add("nan-high/subtract-left",!good(sub(bad,I(2))));
      add("nan-high/subtract-right",!good(sub(I(2),bad)));
      add("nan-high/multiply-left",!good(mul(bad,I(2))));
      add("nan-high/multiply-right",!good(mul(I(2),bad)));
      add("nan-high/divide-left",!good(div(bad,I(2))));
      add("nan-high/divide-right",!good(div(I(2),bad)));
      add("nan-high/minimum-left",!good(minimum(bad,I(2))));
      add("nan-high/minimum-right",!good(minimum(I(2),bad)));
      add("nan-high/maximum-left",!good(maximum(bad,I(2))));
      add("nan-high/maximum-right",!good(maximum(I(2),bad)));
      add("nan-high/norm-left",!good(norm(bad,I(2))));
      add("nan-high/norm-right",!good(norm(I(2),bad)));
      add("nan-high/midpoint",!std::isfinite(midpoint(bad)));
      add("nan-high/mag",!std::isfinite(mag(bad)));
    }
    { const I bad=I(1,inf);
      add("positive-infinity/neg",!good(neg(bad)));
      add("positive-infinity/square",!good(sq(bad)));
      add("positive-infinity/root",!good(root(bad)));
      add("positive-infinity/absolute",!good(abs(bad)));
      add("positive-infinity/widen",!good(widen(bad,1)));
      add("positive-infinity/add-left",!good(detail::add(bad,I(2))));
      add("positive-infinity/add-right",!good(detail::add(I(2),bad)));
      add("positive-infinity/subtract-left",!good(sub(bad,I(2))));
      add("positive-infinity/subtract-right",!good(sub(I(2),bad)));
      add("positive-infinity/multiply-left",!good(mul(bad,I(2))));
      add("positive-infinity/multiply-right",!good(mul(I(2),bad)));
      add("positive-infinity/divide-left",!good(div(bad,I(2))));
      add("positive-infinity/divide-right",!good(div(I(2),bad)));
      add("positive-infinity/minimum-left",!good(minimum(bad,I(2))));
      add("positive-infinity/minimum-right",!good(minimum(I(2),bad)));
      add("positive-infinity/maximum-left",!good(maximum(bad,I(2))));
      add("positive-infinity/maximum-right",!good(maximum(I(2),bad)));
      add("positive-infinity/norm-left",!good(norm(bad,I(2))));
      add("positive-infinity/norm-right",!good(norm(I(2),bad)));
      add("positive-infinity/midpoint",!std::isfinite(midpoint(bad)));
      add("positive-infinity/mag",!std::isfinite(mag(bad)));
    }
    { const I bad=I(-inf,1);
      add("negative-infinity/neg",!good(neg(bad)));
      add("negative-infinity/square",!good(sq(bad)));
      add("negative-infinity/root",!good(root(bad)));
      add("negative-infinity/absolute",!good(abs(bad)));
      add("negative-infinity/widen",!good(widen(bad,1)));
      add("negative-infinity/add-left",!good(detail::add(bad,I(2))));
      add("negative-infinity/add-right",!good(detail::add(I(2),bad)));
      add("negative-infinity/subtract-left",!good(sub(bad,I(2))));
      add("negative-infinity/subtract-right",!good(sub(I(2),bad)));
      add("negative-infinity/multiply-left",!good(mul(bad,I(2))));
      add("negative-infinity/multiply-right",!good(mul(I(2),bad)));
      add("negative-infinity/divide-left",!good(div(bad,I(2))));
      add("negative-infinity/divide-right",!good(div(I(2),bad)));
      add("negative-infinity/minimum-left",!good(minimum(bad,I(2))));
      add("negative-infinity/minimum-right",!good(minimum(I(2),bad)));
      add("negative-infinity/maximum-left",!good(maximum(bad,I(2))));
      add("negative-infinity/maximum-right",!good(maximum(I(2),bad)));
      add("negative-infinity/norm-left",!good(norm(bad,I(2))));
      add("negative-infinity/norm-right",!good(norm(I(2),bad)));
      add("negative-infinity/midpoint",!std::isfinite(midpoint(bad)));
      add("negative-infinity/mag",!std::isfinite(mag(bad)));
    }
    { const I bad=I(-inf,inf);
      add("both-infinities/neg",!good(neg(bad)));
      add("both-infinities/square",!good(sq(bad)));
      add("both-infinities/root",!good(root(bad)));
      add("both-infinities/absolute",!good(abs(bad)));
      add("both-infinities/widen",!good(widen(bad,1)));
      add("both-infinities/add-left",!good(detail::add(bad,I(2))));
      add("both-infinities/add-right",!good(detail::add(I(2),bad)));
      add("both-infinities/subtract-left",!good(sub(bad,I(2))));
      add("both-infinities/subtract-right",!good(sub(I(2),bad)));
      add("both-infinities/multiply-left",!good(mul(bad,I(2))));
      add("both-infinities/multiply-right",!good(mul(I(2),bad)));
      add("both-infinities/divide-left",!good(div(bad,I(2))));
      add("both-infinities/divide-right",!good(div(I(2),bad)));
      add("both-infinities/minimum-left",!good(minimum(bad,I(2))));
      add("both-infinities/minimum-right",!good(minimum(I(2),bad)));
      add("both-infinities/maximum-left",!good(maximum(bad,I(2))));
      add("both-infinities/maximum-right",!good(maximum(I(2),bad)));
      add("both-infinities/norm-left",!good(norm(bad,I(2))));
      add("both-infinities/norm-right",!good(norm(I(2),bad)));
      add("both-infinities/midpoint",!std::isfinite(midpoint(bad)));
      add("both-infinities/mag",!std::isfinite(mag(bad)));
    }
    { const I bad=I(nan,nan);
      add("both-nan/neg",!good(neg(bad)));
      add("both-nan/square",!good(sq(bad)));
      add("both-nan/root",!good(root(bad)));
      add("both-nan/absolute",!good(abs(bad)));
      add("both-nan/widen",!good(widen(bad,1)));
      add("both-nan/add-left",!good(detail::add(bad,I(2))));
      add("both-nan/add-right",!good(detail::add(I(2),bad)));
      add("both-nan/subtract-left",!good(sub(bad,I(2))));
      add("both-nan/subtract-right",!good(sub(I(2),bad)));
      add("both-nan/multiply-left",!good(mul(bad,I(2))));
      add("both-nan/multiply-right",!good(mul(I(2),bad)));
      add("both-nan/divide-left",!good(div(bad,I(2))));
      add("both-nan/divide-right",!good(div(I(2),bad)));
      add("both-nan/minimum-left",!good(minimum(bad,I(2))));
      add("both-nan/minimum-right",!good(minimum(I(2),bad)));
      add("both-nan/maximum-left",!good(maximum(bad,I(2))));
      add("both-nan/maximum-right",!good(maximum(I(2),bad)));
      add("both-nan/norm-left",!good(norm(bad,I(2))));
      add("both-nan/norm-right",!good(norm(I(2),bad)));
      add("both-nan/midpoint",!std::isfinite(midpoint(bad)));
      add("both-nan/mag",!std::isfinite(mag(bad)));
    }
    add("overflow/add",!good(detail::add(I(huge),I(huge))));
    add("overflow/multiply",!good(mul(I(1e200),I(1e200))));
    add("overflow/square-positive",!good(sq(I(1e200))));
    add("overflow/square-negative",!good(sq(I(-1e200))));
    add("overflow/square-straddling",!good(sq(I(-1e200,1e200))));
    add("overflow/divide",!good(div(I(huge),I(.5))));
    add("overflow/reciprocal",!good(div(I(0),I(tiny))));
    add("overflow/widen",!good(widen(I(huge),huge)));
    add("overflow/outward",!good(detail::add(I(huge),I(0))));
    add("overflow/midpoint",!std::isfinite(midpoint(I(-huge,huge))));
    add("domain/divisor-crosses-zero",!good(div(I(1),I(-1,1))));
    add("domain/divisor-zero",!good(div(I(1),I(0))));
    add("domain/root-negative",!good(root(I(-4,-1))));
    add("domain/widen-negative",!good(widen(I(1),-1)));
    add("domain/widen-nan",!good(widen(I(1),nan)));
    add("domain/widen-infinity",!good(widen(I(1),inf)));
    add("chain/root-overflow-remains-invalid",!good(mul(root(detail::add(sq(I(1e200)),I(1))),I(2))));
    add("chain/invalid-minimum-remains-invalid",!good(minimum(I(0),mul(invalid(),I(2)))));
    add("chain/rounded-cavity-overflow",!good(roundedCavityDistance(I(1e200),I(0),EnclosureDimensions{})));
    add("control/zero-square",good(sq(I(0)))&&sq(I(0)).lo==0&&sq(I(0)).hi==up(0));
    add("control/negative-zero-square",good(sq(I(-0.0)))&&sq(I(-0.0)).lo==0&&sq(I(-0.0)).hi==up(0));
    add("control/positive-square",sq(I(2,3)).lo==down(4)&&sq(I(2,3)).hi==up(9));
    add("control/negative-square",sq(I(-3,-2)).lo==down(4)&&sq(I(-3,-2)).hi==up(9));
    add("control/straddling-square",sq(I(-3,2)).lo==0&&sq(I(-3,2)).hi==up(9));
    add("control/root-intersection",root(I(-1,4)).lo==0&&root(I(-1,4)).hi==up(2));
    add("control/multiply",mul(I(-2,3),I(4,5)).lo==down(-10)&&mul(I(-2,3),I(4,5)).hi==up(15));
    add("control/minimum",minimum(I(-2,3),I(4,5)).lo==-2&&minimum(I(-2,3),I(4,5)).hi==3);
    add("control/maximum",maximum(I(-2,3),I(4,5)).lo==4&&maximum(I(-2,3),I(4,5)).hi==5);
    return rows;
}
inline Rows Admission(){Rows rows;
    auto add=[&](const std::string& key,bool value){rows.emplace_back(key,value);};
    // Raw definition floors are document-unit floors; point/radius floors below
    // are physical. Exercise actual validators, not a fabricated accepted DTO.
    for(int plane=0;plane<3;++plane)for(bool framed:{false,true}){
        const std::string tag=std::to_string(plane)+"/"+(framed?"schema2/":"schema1/");
        auto e=probe::identity(1e-200);e.sourceFamily=2;e.sourceSchema=framed?2:1;
        e.axis=std::uint8_t(probe::axis(plane));e.radius=1e197;e.point=probe::point(plane,1e200,0);
        enclosure::Parameters p;p.metersPerUnit=e.metersPerUnit;p.definition.plane=plane;
        if(framed)p.definition.constructionFrame=profile::ConstructionFrame{};
        EnclosureDerivedDimensions dimensions;
        const bool definitionOK=InspectEnclosureDefinition(p.definition,dimensions);
        const bool encoded=enclosure::Encode(p,e.sourceValues);
        enclosure::Parameters decoded;
        const bool decodedOK=encoded&&enclosure::Decode(int(e.sourceSchema),e.sourceValues,decoded);
        std::vector<double> recipeAgain;
        const bool recipeRoundtrip=decodedOK&&enclosure::Encode(decoded,recipeAgain)&&recipeAgain==e.sourceValues;
        const double mm=e.metersPerUnit*1000;
        bool physicalOK=std::isfinite(mm)&&mm>0&&std::isfinite(e.radius*mm)&&e.radius*mm>=.001&&e.radius*mm<=1e6;
        for(double v:e.point)physicalOK=physicalOK&&std::isfinite(v*mm)&&std::abs(v*mm)<=1e6;
        const bool admitted=retained_solid::Valid(e);
        std::vector<std::uint8_t> before,after;retained_solid::Envelope restored;
        const bool wire=retained_solid::Encode(e,before)&&retained_solid::Decode(before,restored)&&retained_solid::Encode(restored,after)&&before==after;
        const auto report=Inspect(e);
        add(tag+"definition-valid",definitionOK&&dimensions.expectedVolume>1e-8);
        add(tag+"raw-dimension-floors",p.definition.dimensions.width==100&&p.definition.dimensions.depth==60&&p.definition.dimensions.height==30&&p.definition.dimensions.wall==2&&p.definition.dimensions.floor==2&&p.definition.dimensions.cornerRadius==4);
        add(tag+"recipe-encode-decode",recipeRoundtrip);
        add(tag+"physical-point-radius-admission",physicalOK);
        add(tag+"full-envelope-valid",admitted);
        add(tag+"full-wire-roundtrip",wire);
        add(tag+"exact-unit-bits",decodedOK&&retained_solid::Bits(decoded.metersPerUnit)==retained_solid::Bits(e.metersPerUnit)&&wire&&retained_solid::Bits(restored.metersPerUnit)==retained_solid::Bits(e.metersPerUnit));
        add(tag+"numeric-uncertain",definitionOK&&recipeRoundtrip&&physicalOK&&admitted&&wire&&report.status==Status::NumericUncertain);
        add(tag+"restored-numeric-uncertain",wire&&Inspect(restored).status==Status::NumericUncertain);
        add(tag+"original-envelope-unchanged",wire&&retained_solid::Encode(e,after)&&after==before);
        add(tag+"finite-normal-control",Inspect(probe::box(.001,plane)).status==Status::ClearRecipeDisk);
    }return rows;
}
}
